apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: iot.argocd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd
                port:
                  number: 443
    - host: iot.playground
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playground
                port:
                  number: 80
        
